create extension if not exists pgcrypto;

do $$ begin
  create type transaction_status as enum ('pending', 'paid', 'failed', 'expired');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type subscription_status as enum ('inactive', 'pending', 'active', 'expired');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  telegram_id text unique,
  telegram_link_token text unique,
  telegram_link_token_expires_at timestamptz,
  email_verified_at timestamptz,
  password text not null,
  remember_token text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_telegram_id_numeric check (telegram_id is null or telegram_id ~ '^[0-9]+$')
);

create table if not exists public.subscription_plans (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price integer not null check (price >= 0),
  duration_days integer not null check (duration_days > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  plan_id bigint not null references public.subscription_plans(id) on delete cascade,
  midtrans_order_id text not null unique,
  status transaction_status not null default 'pending',
  gross_amount integer not null check (gross_amount >= 0),
  payment_type text,
  settlement_time timestamptz,
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists transactions_user_status_idx
  on public.transactions(user_id, status);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  plan_id bigint not null references public.subscription_plans(id) on delete cascade,
  transaction_id bigint references public.transactions(id) on delete set null,
  status subscription_status not null default 'inactive',
  start_date timestamptz,
  end_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_user_status_end_date_idx
  on public.subscriptions(user_id, status, end_date);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at
before update on public.users
for each row execute function public.touch_updated_at();

drop trigger if exists subscription_plans_touch_updated_at on public.subscription_plans;
create trigger subscription_plans_touch_updated_at
before update on public.subscription_plans
for each row execute function public.touch_updated_at();

drop trigger if exists transactions_touch_updated_at on public.transactions;
create trigger transactions_touch_updated_at
before update on public.transactions
for each row execute function public.touch_updated_at();

drop trigger if exists subscriptions_touch_updated_at on public.subscriptions;
create trigger subscriptions_touch_updated_at
before update on public.subscriptions
for each row execute function public.touch_updated_at();

alter table public.users enable row level security;
alter table public.subscription_plans enable row level security;
alter table public.transactions enable row level security;
alter table public.subscriptions enable row level security;

drop policy if exists "public can read subscription plans" on public.subscription_plans;
create policy "public can read subscription plans"
on public.subscription_plans
for select
to anon, authenticated
using (true);
