-- Social Media Analysis module.
-- Additive migration only: reuses existing users, transactions, and payment flow.
-- Medsos packages are one-time purchases, not recurring subscriptions.

create extension if not exists pgcrypto;

alter table public.transactions
add column if not exists product_type text not null default 'financial_subscription';

alter table public.subscription_plans
add column if not exists product_type text not null default 'financial_subscription';

do $$ begin
  create type medsos_entitlement_status as enum (
    'pending_payment',
    'active',
    'consumed',
    'expired',
    'refunded',
    'cancelled'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type medsos_request_status as enum (
    'queued',
    'validating',
    'scraping',
    'ai_processing',
    'generating_report',
    'completed',
    'failed',
    'cancelled',
    'retry_wait'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type medsos_platform as enum (
    'instagram',
    'tiktok',
    'youtube'
  );
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type medsos_artifact_type as enum (
    'scraped_json',
    'html_snapshot',
    'screenshot',
    'ai_raw',
    'report_json',
    'report_pdf',
    'other'
  );
exception
  when duplicate_object then null;
end $$;

create table if not exists public.medsos_packages (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  financial_plan_id bigint unique references public.subscription_plans(id) on delete set null,
  purchase_type text not null default 'one_time' check (purchase_type = 'one_time'),
  description text,
  price integer not null check (price >= 0),
  quota_limit integer not null check (quota_limit > 0),
  validity_days integer not null check (validity_days > 0),
  features jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.medsos_entitlements (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  transaction_id bigint not null unique references public.transactions(id) on delete restrict,
  package_id bigint not null references public.medsos_packages(id) on delete restrict,
  status medsos_entitlement_status not null default 'pending_payment',
  quota_total integer not null check (quota_total > 0),
  quota_used integer not null default 0 check (quota_used >= 0),
  activated_at timestamptz,
  expires_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint medsos_entitlements_quota_used_lte_total check (quota_used <= quota_total)
);

create index if not exists medsos_entitlements_user_status_idx
  on public.medsos_entitlements(user_id, status);

create index if not exists medsos_entitlements_package_status_idx
  on public.medsos_entitlements(package_id, status);

create table if not exists public.medsos_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  entitlement_id bigint not null references public.medsos_entitlements(id) on delete cascade,
  platform medsos_platform not null,
  profile_url text not null,
  notes text,
  status medsos_request_status not null default 'queued',
  progress_percent integer not null default 0 check (progress_percent >= 0 and progress_percent <= 100),
  current_step text,
  n8n_execution_id text,
  callback_token text not null default encode(gen_random_bytes(24), 'hex'),
  retry_count integer not null default 0 check (retry_count >= 0),
  max_retries integer not null default 3 check (max_retries >= 0),
  quota_charged boolean not null default true,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  failed_at timestamptz,
  error_code text,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists medsos_requests_user_status_created_idx
  on public.medsos_requests(user_id, status, created_at desc);

create index if not exists medsos_requests_entitlement_idx
  on public.medsos_requests(entitlement_id);

create index if not exists medsos_requests_n8n_execution_idx
  on public.medsos_requests(n8n_execution_id);

create index if not exists medsos_requests_status_progress_idx
  on public.medsos_requests(status, progress_percent);

create table if not exists public.medsos_analysis_results (
  id bigint generated by default as identity primary key,
  request_id bigint not null unique references public.medsos_requests(id) on delete cascade,
  summary text,
  sentiment_label text,
  sentiment_score numeric(5, 4),
  sentiment_breakdown jsonb not null default '{}'::jsonb,
  engagement_score numeric(5, 2),
  engagement_metrics jsonb not null default '{}'::jsonb,
  top_topics jsonb not null default '[]'::jsonb,
  audience_insight jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  charts_data jsonb not null default '{}'::jsonb,
  raw_payload jsonb,
  model_version text,
  generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists medsos_analysis_results_generated_at_idx
  on public.medsos_analysis_results(generated_at desc);

create table if not exists public.medsos_artifacts (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.medsos_requests(id) on delete cascade,
  artifact_type medsos_artifact_type not null,
  storage_provider text not null,
  storage_path text not null,
  public_url text,
  checksum text,
  payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists medsos_artifacts_request_idx
  on public.medsos_artifacts(request_id, artifact_type);

create table if not exists public.medsos_request_events (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.medsos_requests(id) on delete cascade,
  event_type text not null,
  step_name text,
  status medsos_request_status,
  message text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists medsos_request_events_request_created_idx
  on public.medsos_request_events(request_id, created_at desc);

create index if not exists medsos_request_events_event_type_idx
  on public.medsos_request_events(event_type);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists medsos_packages_touch_updated_at on public.medsos_packages;
create trigger medsos_packages_touch_updated_at
before update on public.medsos_packages
for each row execute function public.touch_updated_at();

drop trigger if exists medsos_entitlements_touch_updated_at on public.medsos_entitlements;
create trigger medsos_entitlements_touch_updated_at
before update on public.medsos_entitlements
for each row execute function public.touch_updated_at();

drop trigger if exists medsos_requests_touch_updated_at on public.medsos_requests;
create trigger medsos_requests_touch_updated_at
before update on public.medsos_requests
for each row execute function public.touch_updated_at();

drop trigger if exists medsos_analysis_results_touch_updated_at on public.medsos_analysis_results;
create trigger medsos_analysis_results_touch_updated_at
before update on public.medsos_analysis_results
for each row execute function public.touch_updated_at();

drop trigger if exists medsos_artifacts_touch_updated_at on public.medsos_artifacts;
create trigger medsos_artifacts_touch_updated_at
before update on public.medsos_artifacts
for each row execute function public.touch_updated_at();

alter table public.medsos_packages enable row level security;
alter table public.medsos_entitlements enable row level security;
alter table public.medsos_requests enable row level security;
alter table public.medsos_analysis_results enable row level security;
alter table public.medsos_artifacts enable row level security;
alter table public.medsos_request_events enable row level security;

drop policy if exists "public can read active medsos packages" on public.medsos_packages;
create policy "public can read active medsos packages"
on public.medsos_packages
for select
to anon, authenticated
using (active = true);

drop policy if exists "service role can manage medsos packages" on public.medsos_packages;
create policy "service role can manage medsos packages"
on public.medsos_packages
for all
to service_role
using (true)
with check (true);

drop policy if exists "service role can manage medsos entitlements" on public.medsos_entitlements;
create policy "service role can manage medsos entitlements"
on public.medsos_entitlements
for all
to service_role
using (true)
with check (true);

drop policy if exists "service role can manage medsos requests" on public.medsos_requests;
create policy "service role can manage medsos requests"
on public.medsos_requests
for all
to service_role
using (true)
with check (true);

drop policy if exists "service role can manage medsos analysis results" on public.medsos_analysis_results;
create policy "service role can manage medsos analysis results"
on public.medsos_analysis_results
for all
to service_role
using (true)
with check (true);

drop policy if exists "service role can manage medsos artifacts" on public.medsos_artifacts;
create policy "service role can manage medsos artifacts"
on public.medsos_artifacts
for all
to service_role
using (true)
with check (true);

drop policy if exists "service role can manage medsos request events" on public.medsos_request_events;
create policy "service role can manage medsos request events"
on public.medsos_request_events
for all
to service_role
using (true)
with check (true);

insert into public.subscription_plans (name, price, duration_days)
values
  ('Medsos Basic Package', 49000, 30),
  ('Medsos Pro Package', 149000, 60),
  ('Medsos Premium Package', 299000, 90)
on conflict (name) do update
set price = excluded.price,
    duration_days = excluded.duration_days,
    product_type = 'medsos_package',
    updated_at = now();

update public.subscription_plans
set product_type = 'medsos_package'
where name in ('Medsos Basic Package', 'Medsos Pro Package', 'Medsos Premium Package');

insert into public.medsos_packages (
  code,
  name,
  financial_plan_id,
  description,
  price,
  quota_limit,
  validity_days,
  features
)
select
  values_table.code,
  values_table.name,
  subscription_plans.id,
  values_table.description,
  values_table.price,
  values_table.quota_limit,
  values_table.validity_days,
  values_table.features::jsonb
from (
  values
    (
      'basic',
      'Basic',
      'One-time package untuk satu analisis social media.',
      49000,
      1,
      30,
      '["1 analysis", "AI summary", "Sentiment analysis"]'
    ),
    (
      'pro',
      'Pro',
      'Paket untuk beberapa analisis dengan insight engagement dan audience.',
      149000,
      5,
      60,
      '["5 analysis", "Engagement analysis", "Audience insight"]'
    ),
    (
      'premium',
      'Premium',
      'Paket advanced untuk report lebih dalam dan competitor insight.',
      299000,
      15,
      90,
      '["15 analysis", "Competitor insight", "Advanced AI report"]'
    )
) as values_table(code, name, description, price, quota_limit, validity_days, features)
join public.subscription_plans
  on subscription_plans.name = 'Medsos ' || values_table.name || ' Package'
on conflict (code) do update
set name = excluded.name,
    financial_plan_id = excluded.financial_plan_id,
    description = excluded.description,
    price = excluded.price,
    quota_limit = excluded.quota_limit,
    validity_days = excluded.validity_days,
    features = excluded.features,
    active = true,
    updated_at = now();
